version: "3"
services:

  clickhouse:
    container_name: clickhouse
    image: yandex/clickhouse-server
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - ./clickhouse-data:/var/lib/clickhouse/
      - ./config.xml:/etc/clickhouse-server/config.xml
      - ./users.xml:/etc/clickhouse-server/users.xml
  
  tabix:
    container_name: tabix
    image: spoonest/clickhouse-tabix-web-client
    depends_on:
      - clickhouse
    ports:
      - 8080:80
    environment:
      CH_NAME: "local clickhouse"
      CH_HOST: "clickhouse:8123"
      CH_LOGIN: default
      CH_PASSWORD: ""
