version: '3.1'
services :

  backend_db:
    image: postgres
    container_name: backend_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db

  airflow:
    build: .
    container_name: airflow
    depends_on:
      - backend_db
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/root/airflow/dags
      - ./test:/root/airflow/test
      - ./plugins:/root/airflow/plugins

      - ./airflow.cfg:/root/airflow/airflow.cfg
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./start.sh:/start.sh
