version: '3.1'
services :

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    depends_on: 
      - postgres
    ports:
      - 8080:8080
